Sos iris experimental
AlexandreAmice/drake pull request #12
Opened 2022-01-15 21:17 UTC by AlexandreAmice

This allows for us to run Iris in the tangent space of the configuration space.

2022-01-16 06:53 UTC, hongkai-dai requested changes
PTAL. Sorry for the reviewing this late, I was mostly reviewing a journal paper today.

> Reviewed 5 of 12 files at r1, 1 of 1 files at r2, 11 of 13 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/12#-:-MtWeKxJA5IutEpMYijD:bqrtcqy)* status: 19 of 20 files reviewed, 16 unresolved discussions (waiting on @AlexandreAmice and @hongkai-dai)

___
*[bindings/pydrake/geometry_py_optimization.cc, line 247 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWe8C-COIIvwX2RWka:-MtWe8C-COIIvwX2RWkb:b-5rlmtn) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/bindings/pydrake/geometry_py_optimization.cc#L247)):*
> ```cpp
>           &IrisOptionsRationalSpace::relative_termination_threshold,
>           doc.IrisOptions.relative_termination_threshold.doc)
>       .def_readwrite("configuration_space_margin",
> ```

I didn't see this data field in IrisOptionsRationalSpace.
___
*[geometry/optimization/hpolyhedron.h, line 59 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWMLU2BEmN1REuSwpB:-MtWMLU2BEmN1REuSwpC:bo6q1k9) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/hpolyhedron.h#L59)):*
> ```objc
>    * @return
>    */
>   bool ContainedInOtherHPolyhedron(const HPolyhedron other) const;
> ```

const HPolyhedron& other, namely better to use copy-by-reference rather than the expensive copy-by-value.
___
*[geometry/optimization/hpolyhedron.cc, line 181 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWMnut8nREEMk19GJ3:-MtWMnut8nREEMk19GJ4:b-xbcn98) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/hpolyhedron.cc#L181)):*
> ```cpp
> 
> //TODO: need to add tests for this
> bool HPolyhedron::ContainedInOtherHPolyhedron(const HPolyhedron other) const {
> ```

BTW, I am not sure if you have considered this already, but an alternative approach is to consider using the duality theory. Namely if the polyhedron Ax<=b is contained in polyhedron Cx<=d, by duality theory, it means for each row of Cx<=d, there exists λᵢ >= 0 satisfying Aᵀλᵢ = cᵢ, dᵢ−λᵢᵀb≥ 0, where cᵢ, dᵢ are the i'th row of C, d respectively. We can solve these LPs to determine the containment. Each of LP is a feasibility problem instead of a maximization problem, which might be a bit easier to solve?
___
*[geometry/optimization/hpolyhedron.cc, line 182 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWOQwC2XbqN3atlm70:-MtWOQwC2XbqN3atlm71:baat8au) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/hpolyhedron.cc#L182)):*
> ```cpp
> //TODO: need to add tests for this
> bool HPolyhedron::ContainedInOtherHPolyhedron(const HPolyhedron other) const {
>   DRAKE_DEMAND(other.A().rows() == A_.rows());
> ```

Why they need to have same number of rows? I would think they need to have the same number of columns?
___
*[geometry/optimization/hpolyhedron.cc, line 186 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWOixrAbnhMkJeFyJs:-MtWOixrAbnhMkJeFyJt:b9njvfs) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/hpolyhedron.cc#L186)):*
> ```cpp
>   solvers::MathematicalProgram prog;
>   solvers::VectorXDecisionVariable x =
>         prog.NewContinuousVariables(A_.rows(), "x");
> ```

This should be A_.cols()?
___
*[geometry/optimization/hpolyhedron.cc, line 197 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWPj865e0FWBKcAF-j:-MtWPj865e0FWBKcAF-k:b-vsx5mk) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/hpolyhedron.cc#L197)):*
> ```cpp
> 
>   for(int i = 0; i < other.A().rows(); i++){
>     redundant_constraint_binding.evaluator()->UpdateCoefficients(
> ```

Curious why we need this constraint, I thought you can check if the maximization of
max other.A.row(i) * x
s.t    A * x <= b
is larger than other.b(i) or not. 
___
*[geometry/optimization/hpolyhedron.cc, line 203 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWQEIp1pVQeCNVaY8r:-MtWQEIp1pVQeCNVaY8s:bstf0m7) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/hpolyhedron.cc#L203)):*
> ```cpp
>     auto result = solvers::Solve(prog);
> 
>     // constraints define an empty set or the current inequality of other is not redundant
> ```

Technically, if this polyhedron is empty, then an empty set should be contained in any other set, so this should return true if the program is infeasible.
___
*[geometry/optimization/iris.h, line 174 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWS2nr4_Mrm7q8r9A8:-MtWS2nr4_Mrm7q8r9A9:b4tk4la) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/iris.h#L174)):*
> ```objc
>   /** For IRIS in rational configuration space we need a point around which to perform the stereographic projection
>    * */
>   Eigen::VectorXd* q_star_ptr = nullptr;
> ```

I am curious why you need to store q_star and hpolyhedron inside this struct. As far as I can see, these two can be used as the function input argument where you also pass in an `IrisOptionRationalSpace`, namely if you have a function that uses `IrisOptionRationalSpace`, that function can be
```cc
void foo(const std::optional<Eigen::VectorXd>& q_star, const std::optional<HPolyhedron>& starting_hpolyhedron, const IrisOptionRationalSpace& option);
```

then you can avoid a lot of the dangling pointer problem as mentioned below.
___
*[geometry/optimization/iris.h, line 182 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWRDZxCmykriNS_AAy:-MtWRDZxCmykriNS_AAz:b-czcvj5) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/iris.h#L182)):*
> ```objc
>   {
>     Eigen::VectorXd q_star_copy = q_star;
>     q_star_ptr = &q_star_copy;
> ```

q_star_ptr will be a dangling pointer after this function exits (the local variable q_star_copy) is destroyed after this function exits.
___
*[geometry/optimization/iris.h, line 191 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWRlLO4HV-nccplsqG:-MtWRlLO4HV-nccplsqH:b-vtds3h) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/iris.h#L191)):*
> ```objc
>   void set_starting_hpolyhedron(const HPolyhedron P)
>   {
>     HPolyhedron P_copy = P;
> ```

Same here, this P_copy will be destroyed after function exits, and `starting_hpolyhedron_ptr` becomes a dangling pointer, causing segmentation fault later. 
___
*[geometry/optimization/iris.h, line 211 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWT708-kioDRBx5nJ3:-MtWT7098bQuOI_NqIBJ:bykbam0) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/iris.h#L211)):*
> ```objc
> @param context is a context of the @p plant. The context must have the positions
> of the plant set to the initialIRIS seed configuration.
> @param q_star is the point from which the stereographic projection is computed
> ```

q_star, C0, d0 are missing from the function input argument.
___
*[geometry/optimization/iris.cc, line 389 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWXlWZEHfQQb9Yygd4:-MtWXlW_D3Xh1BV1_ujz:b-50n8rs) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/iris.cc#L389)):*
> ```cpp
>         Jt_v_WB(3, plant_->num_positions());
>     for (int i = 0; i < plant_->num_positions(); i++){
>       // dX_t_wa = dJ_q_WA * dq_dt
> ```

The documentation should be `J_q_WA` instead of `dJ_q_WA`?
___
*[geometry/optimization/iris. [...]

2022-01-17 22:32 UTC, AlexandreAmice reviewed
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/12)* status: 12 of 20 files reviewed, 16 unresolved discussions (waiting on @AlexandreAmice and @hongkai-dai)

___
*[bindings/pydrake/geometry_py_optimization.cc, line 247 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWe8C-COIIvwX2RWka:-MtdO5tiEUlcEm6ALLs3:b-6f7cqz) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/bindings/pydrake/geometry_py_optimization.cc#L247)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I didn't see this data field in IrisOptionsRationalSpace.
</blockquote></details>

It is inheritted from the IrisOptions struct in iris.h
___
*[geometry/optimization/hpolyhedron.cc, line 181 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWMnut8nREEMk19GJ3:-MtdP4vT6X6zj7tcw4dA:b-5irpu9) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/hpolyhedron.cc#L181)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, I am not sure if you have considered this already, but an alternative approach is to consider using the duality theory. Namely if the polyhedron Ax<=b is contained in polyhedron Cx<=d, by duality theory, it means for each row of Cx<=d, there exists λᵢ >= 0 satisfying Aᵀλᵢ = cᵢ, dᵢ−λᵢᵀb≥ 0, where cᵢ, dᵢ are the i'th row of C, d respectively. We can solve these LPs to determine the containment. Each of LP is a feasibility problem instead of a maximization problem, which might be a bit easier to solve?
</blockquote></details>

This might perform the check faster for very large polyhedra. This is a good point
___
*[geometry/optimization/hpolyhedron.cc, line 182 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWOQwC2XbqN3atlm70:-MtdPMWF19W0-4lTi5PM:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/hpolyhedron.cc#L182)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why they need to have same number of rows? I would think they need to have the same number of columns?
</blockquote></details>

Done.
___
*[geometry/optimization/hpolyhedron.cc, line 186 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWOixrAbnhMkJeFyJs:-MtdPfT-2LhkZpyiCBhI:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/hpolyhedron.cc#L186)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This should be A_.cols()?
</blockquote></details>

Done.
___
*[geometry/optimization/hpolyhedron.cc, line 197 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWPj865e0FWBKcAF-j:-MtdPnqYBOH8jpbA9QBr:b-88yfvo) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/hpolyhedron.cc#L197)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Curious why we need this constraint, I thought you can check if the maximization of
max other.A.row(i) * x
s.t    A * x <= b
is larger than other.b(i) or not. 
</blockquote></details>

This ensures a bounded objective which I assumed would be helpful for speeding up the solver
___
*[geometry/optimization/hpolyhedron.cc, line 203 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWQEIp1pVQeCNVaY8r:-MtdQJ-V1HbKMBUa170q:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/hpolyhedron.cc#L203)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Technically, if this polyhedron is empty, then an empty set should be contained in any other set, so this should return true if the program is infeasible.
</blockquote></details>

Done.
___
*[geometry/optimization/iris.h, line 174 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWS2nr4_Mrm7q8r9A8:-MtdQS0S3cbqVG6LR_-w:bun94wr) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/iris.h#L174)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am curious why you need to store q_star and hpolyhedron inside this struct. As far as I can see, these two can be used as the function input argument where you also pass in an `IrisOptionRationalSpace`, namely if you have a function that uses `IrisOptionRationalSpace`, that function can be
```cc
void foo(const std::optional<Eigen::VectorXd>& q_star, const std::optional<HPolyhedron>& starting_hpolyhedron, const IrisOptionRationalSpace& option);
```

then you can avoid a lot of the dangling pointer problem as mentioned below.
</blockquote></details>

I think the hpolyhedron makes sense as an input to the iris function, but I still think having q_star explicitly defined in the options is better. The regions in tangent space don't make sense if we don't know the location about which the stereographic projection was performed. Since I can't leave this specified in HPolyhedron, i think it makes sense that the user be able to store this permanently in another struct that they need to define anyway.
___
*[geometry/optimization/iris.cc, line 734 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtW_fVO5vz3bR7oFPwV:-MtdTKVJ8mHuJDQVD7FW:bqo93zh) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/iris.cc#L734)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Not sure why we need this.
</blockquote></details>

Ensures that the starting HPolyhedron doesn't exceed the joint limits.
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 85 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWcNiwDovwr3JSqKkA:-Mte9wH58gR2kW98CWWE:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/multibody/rational_forward_kinematics/cspace_free_region.h#L85)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Just for debugging and testing purpose (it is used in cspace_free_region_test.cc).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-17 23:40 UTC, hongkai-dai requested changes
> Reviewed 5 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/12)* status: 17 of 20 files reviewed, 10 unresolved discussions (waiting on @AlexandreAmice and @hongkai-dai)

___
*[geometry/optimization/hpolyhedron.h, line 62 at r5](https://reviewable.io/reviews/alexandreamice/drake/12#-MteJQhSEP9J1tDNCGrI:-MteJQhSEP9J1tDNCGrJ:bdcsmre) ([raw file](https://github.com/alexandreamice/drake/blob/642b8a3807ce15f5d855f0cc090a95701b7697a2/geometry/optimization/hpolyhedron.h#L62)):*
> ```objc
> 
> 
>   /** Add the irredundant inequalities from @p other to the inequalities from this polytope and return the union.
> ```

I think this documentation isn't clear enough. When I read the documentation, I thought the function first finds the irredundant inequalities from other (without considering this polytope), and then append these irredundant inequalities to this polytope.

What it actually implements is that attempt to add each row of the inequalities in other to inequality of this polytope, and skip that row if that row is redundant after appending to the existing inequalities.
___
*[geometry/optimization/hpolyhedron.cc, line 197 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWPj865e0FWBKcAF-j:-MteHd_pALSrV8j2hnon:b8moyek) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/hpolyhedron.cc#L197)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This ensures a bounded objective which I assumed would be helpful for speeding up the solver
</blockquote></details>

I see, could you document it here? Thanks!
___
*[geometry/optimization/hpolyhedron.cc, line 204 at r5](https://reviewable.io/reviews/alexandreamice/drake/12#-MteHtSl2O6jXW3EWayI:-MteHtSl2O6jXW3EWayJ:b-atfzkk) ([raw file](https://github.com/alexandreamice/drake/blob/642b8a3807ce15f5d855f0cc090a95701b7697a2/geometry/optimization/hpolyhedron.cc#L204)):*
> ```cpp
> 
>     // constraints define an empty set or the current inequality of other is not redundant
>     if(!result.is_success()) { return true;}
> ```

When result.is_success() != true, could you check the actual solution result? The optimization could fail due to numerical reasons. So maybe check
```cc
if (result.get_solution_result() == solvers::SolutionResult::kInfeasibleConstraints || result.get_solution_result() == solvers::SolutionResult::kInfeasible_Or_Unbounded) {
  return true;
}
```
___
*[geometry/optimization/hpolyhedron.cc, line 212 at r5](https://reviewable.io/reviews/alexandreamice/drake/12#-MteITwUAlK1W0leDgtB:-MteITwUAlK1W0leDgtC:buyloi3) ([raw file](https://github.com/alexandreamice/drake/blob/642b8a3807ce15f5d855f0cc090a95701b7697a2/geometry/optimization/hpolyhedron.cc#L212)):*
> ```cpp
> }
> 
> //TODO: need to add tests for this
> ```

BTW, if you run a lint test here, it will say that each TODO should have a name. So it should be TODO(Alex.Amice) here.
___
*[geometry/optimization/hpolyhedron.cc, line 217 at r5](https://reviewable.io/reviews/alexandreamice/drake/12#-MteJ1CqA4ExyveYk0Zy:-MteJ1CqA4ExyveYk0Zz:b-q7zafb) ([raw file](https://github.com/alexandreamice/drake/blob/642b8a3807ce15f5d855f0cc090a95701b7697a2/geometry/optimization/hpolyhedron.cc#L217)):*
> ```cpp
>   const double kInf = std::numeric_limits<double>::infinity();
> 
>   Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor> A(
> ```

Curious why you want to use RowMajor here. As far as I can see the default column major also works?
___
*[geometry/optimization/hpolyhedron.cc, line 241 at r5](https://reviewable.io/reviews/alexandreamice/drake/12#-MteKZne9mVPTI0Y66i9:-MteKZne9mVPTI0Y66iA:b9066nv) ([raw file](https://github.com/alexandreamice/drake/blob/642b8a3807ce15f5d855f0cc090a95701b7697a2/geometry/optimization/hpolyhedron.cc#L241)):*
> ```cpp
>         other.A().row(i), Eigen::VectorXd::Constant(1, -kInf),
>         other.b().row(i) + Eigen::VectorXd::Ones(1));
>     program_cost_binding.evaluator()->UpdateCoefficients(-other.A().row(0), 0);
> ```

Should it be other.A().row(i) here instead of other.A().row(0)?
___
*[geometry/optimization/hpolyhedron.cc, line 245 at r5](https://reviewable.io/reviews/alexandreamice/drake/12#-MteKsR28RSYsswZM-YE:-MteKsR28RSYsswZM-YF:bxibcmd) ([raw file](https://github.com/alexandreamice/drake/blob/642b8a3807ce15f5d855f0cc090a95701b7697a2/geometry/optimization/hpolyhedron.cc#L245)):*
> ```cpp
> 
>     // constraints define an empty set or the current inequality of other is not redundant
>     if(!result.is_success() or -result.get_optimal_cost() > other.b()(i)){
> ```

As mentioned above, checking result.is_success() is not enough, result.is_success() = false can be caused by program being infeasible, unbounded, iteration limit, numerical issue, etc.

When the program is infeasible, it is hard to determine whether this new constraint is redundant or not (if the existing constraints are already infeasible, then this new constraint is redundant; OTOH, if the existing constraints are feasible, then this new constraint is not redundant).

BTW, I think it is worth checking if the program is unbounded. I can't guarantee that when the program is unbounded `result.get_optimal_cost()` is always set to -infinity. (It should, but I don't know if we always enforce that).

Most of time you can check if the program is unbounded by 
```cc
result.get_solution_result() == solvers::SolutionResult::kUnbounded
```
The caveat is that for Gurobi, by default it doesn't differentiate from program being infeasible VS program being unbounded. To enforce Gurobi to make that distinction, you will need to do this
```cc
prog.SetSolverOption(GurobiSolver::id(), "DualReductions", 0);
```
___
*[geometry/optimization/iris.h, line 174 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWS2nr4_Mrm7q8r9A8:-MteNMebAhH9DqqYXlMB:b-8e4jgf) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/iris.h#L174)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I think the hpolyhedron makes sense as an input to the iris function, but I still think having q_star explicitly defined in the options is better. The regions in tangent space don't make sense if we don't know the location about which the stereographic projection was performed. Since I can't leave this specified in HPolyhedron, i think it makes sense that the user be able to store this permanently in another struct that they need to define anyway.
</blockquote></details>

I see, if the user always need to provide q_star, why use it as `std::optional<Eigen::VectorXd>`? Why not to use the type as `Eigen::VectorXd`? Do you want to say that if q_str == std::nullopt, then use Eigen::VectorXd::Zero(nq) as the default value? If so, better to document it.
___
*[geometry/optimization/iris.h, line 211 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWT708-kioDRBx5nJ3:-MteOF09ELGLKFZu_rAi:bbkp5hc) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/iris.h#L211)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

q_star, C0, d0 are missing from the function input argument.
</blockquote></details>

Document starting_hpolyhedron? 
___
*[geometry/optimization/iris.h, line 201 at r5](https://reviewable.io/reviews/alexandreamice/drake/12#-MteORr4EtZH0J-puKDm:-MteORr4EtZH0J-puKDn:bu9zzpi) ([raw file](https://github.com/alexandreamice/drake/blob/642b8a3807ce15f5d855f0cc090a95701b7697a2/geometry/optimization/iris.h#L201)):*
> ```objc
>  * Default version of IrisInRationalConfigurationSpace where the starting HPolyhedron is the joint limits of the plant
>  */
> HPolyhedron IrisInRationalConfigurationSpace(
> ```

Curious why providing this overloaded function here? I suppose you can call 
```cc
HPolyhedron  [...]

2022-01-18 03:27 UTC, AlexandreAmice reviewed
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/12)* status: 17 of 20 files reviewed, 10 unresolved discussions (waiting on @hongkai-dai)

___
*[geometry/optimization/hpolyhedron.h, line 62 at r5](https://reviewable.io/reviews/alexandreamice/drake/12#-MteJQhSEP9J1tDNCGrI:-Mtf6poT-0fAOqk0ldEe:b-yeyki8) ([raw file](https://github.com/alexandreamice/drake/blob/642b8a3807ce15f5d855f0cc090a95701b7697a2/geometry/optimization/hpolyhedron.h#L62)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think this documentation isn't clear enough. When I read the documentation, I thought the function first finds the irredundant inequalities from other (without considering this polytope), and then append these irredundant inequalities to this polytope.

What it actually implements is that attempt to add each row of the inequalities in other to inequality of this polytope, and skip that row if that row is redundant after appending to the existing inequalities.
</blockquote></details>

Changing name of function to IrredundantIntersection (this is more accurate of a name) and will change documentation
___
*[geometry/optimization/hpolyhedron.cc, line 197 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWPj865e0FWBKcAF-j:-Mtf8CvA71BrMjow-WYt:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/hpolyhedron.cc#L197)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see, could you document it here? Thanks!
</blockquote></details>

Done.
___
*[geometry/optimization/hpolyhedron.cc, line 204 at r5](https://reviewable.io/reviews/alexandreamice/drake/12#-MteHtSl2O6jXW3EWayI:-Mtf8OEQA7-AguFTjtmw:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/642b8a3807ce15f5d855f0cc090a95701b7697a2/geometry/optimization/hpolyhedron.cc#L204)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

When result.is_success() != true, could you check the actual solution result? The optimization could fail due to numerical reasons. So maybe check
```cc
if (result.get_solution_result() == solvers::SolutionResult::kInfeasibleConstraints || result.get_solution_result() == solvers::SolutionResult::kInfeasible_Or_Unbounded) {
  return true;
}
```
</blockquote></details>

Done.
___
*[geometry/optimization/hpolyhedron.cc, line 217 at r5](https://reviewable.io/reviews/alexandreamice/drake/12#-MteJ1CqA4ExyveYk0Zy:-Mtf8sfqA6Hv3CWBasq8:b-20q4g4) ([raw file](https://github.com/alexandreamice/drake/blob/642b8a3807ce15f5d855f0cc090a95701b7697a2/geometry/optimization/hpolyhedron.cc#L217)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Curious why you want to use RowMajor here. As far as I can see the default column major also works?
</blockquote></details>

Column major ordering would work, but as I will be allocating this matrix row by row, I believe row major ordering is slightly faster as the entries of will form contiguous blocks. I stole this trick off of Russ who uses this in multiple spots in iris.cc (see lines 611 and 507).
___
*[geometry/optimization/hpolyhedron.cc, line 241 at r5](https://reviewable.io/reviews/alexandreamice/drake/12#-MteKZne9mVPTI0Y66i9:-Mtf9XVYAZkg4tCbmujG:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/642b8a3807ce15f5d855f0cc090a95701b7697a2/geometry/optimization/hpolyhedron.cc#L241)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should it be other.A().row(i) here instead of other.A().row(0)?
</blockquote></details>

Done.
___
*[geometry/optimization/hpolyhedron.cc, line 245 at r5](https://reviewable.io/reviews/alexandreamice/drake/12#-MteKsR28RSYsswZM-YE:-Mtf9rrX5_OE6FDgN8H3:bs7wumx) ([raw file](https://github.com/alexandreamice/drake/blob/642b8a3807ce15f5d855f0cc090a95701b7697a2/geometry/optimization/hpolyhedron.cc#L245)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

As mentioned above, checking result.is_success() is not enough, result.is_success() = false can be caused by program being infeasible, unbounded, iteration limit, numerical issue, etc.

When the program is infeasible, it is hard to determine whether this new constraint is redundant or not (if the existing constraints are already infeasible, then this new constraint is redundant; OTOH, if the existing constraints are feasible, then this new constraint is not redundant).

BTW, I think it is worth checking if the program is unbounded. I can't guarantee that when the program is unbounded `result.get_optimal_cost()` is always set to -infinity. (It should, but I don't know if we always enforce that).

Most of time you can check if the program is unbounded by 
```cc
result.get_solution_result() == solvers::SolutionResult::kUnbounded
```
The caveat is that for Gurobi, by default it doesn't differentiate from program being infeasible VS program being unbounded. To enforce Gurobi to make that distinction, you will need to do this
```cc
prog.SetSolverOption(GurobiSolver::id(), "DualReductions", 0);
```
</blockquote></details>

Done. 
___
*[geometry/optimization/iris.h, line 174 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWS2nr4_Mrm7q8r9A8:-MtfA4Hh7y4FF-Y-NqRA:b5952uw) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/iris.h#L174)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see, if the user always need to provide q_star, why use it as `std::optional<Eigen::VectorXd>`? Why not to use the type as `Eigen::VectorXd`? Do you want to say that if q_str == std::nullopt, then use Eigen::VectorXd::Zero(nq) as the default value? If so, better to document it.
</blockquote></details>

I am unsure whether we should enforce that the user must provide this option. In the rational forward kinematics code, you made the choice to force the user to specify q_star every time the function is called. My preference would be to force the user to declare the q_star on the construction of a RationalForwardKinematics object. 

In either case, given your code it would be consistent to demand that the user specify a q_star. However, I believe it is natural to assume the stereographic projection is taken at the 0 point unless there is a good reason for it not to be in which case defaulting to 0 would be the best option. What do you think?
___
*[geometry/optimization/iris.h, line 211 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWT708-kioDRBx5nJ3:-MtfBFRW20U1KMw8yiGd:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/iris.h#L211)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Document starting_hpolyhedron? 
</blockquote></details>

Done.
___
*[geometry/optimization/iris.h, line 201 at r5](https://reviewable.io/reviews/alexandreamice/drake/12#-MteORr4EtZH0J-puKDm:-MtfBPagDynCLUmhld6e:b-8j1hs5) ([raw file](https://github.com/alexandreamice/drake/blob/642b8a3807ce15f5d855f0cc090a95701b7697a2/geometry/optimization/iris.h#L201)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Curious why providing this overloaded function here? I suppose you can call 
```cc
HPolyhedron IrisInRationalConfigurationSpace(
    const multibody::MultibodyPlant<double>& plant,
    const systems::Context<double>& context,
    const std::optional<HPolyhedron>& starting_hpolyhedron,
    const IrisOptionsRationalSpace& options = IrisOptionsRationalSpace())
```
with `starting_hpolyhedron=std::nullopt`.

</blockquote></details>

Did not know this was an option. Change implemented by switching order of starting_hpolyhedron and IrisOptionsRationalS [...]

2022-01-18 03:45 UTC, hongkai-dai requested changes
> Reviewed 1 of 7 files at r5, 3 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/12)* status: 15 of 20 files reviewed, 4 unresolved discussions (waiting on @AlexandreAmice and @hongkai-dai)

___
*[geometry/optimization/hpolyhedron.cc, line 217 at r5](https://reviewable.io/reviews/alexandreamice/drake/12#-MteJ1CqA4ExyveYk0Zy:-MtfEYDq4VI-mAj59-pO:b-kufkxf) ([raw file](https://github.com/alexandreamice/drake/blob/642b8a3807ce15f5d855f0cc090a95701b7697a2/geometry/optimization/hpolyhedron.cc#L217)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Column major ordering would work, but as I will be allocating this matrix row by row, I believe row major ordering is slightly faster as the entries of will form contiguous blocks. I stole this trick off of Russ who uses this in multiple spots in iris.cc (see lines 611 and 507).
</blockquote></details>

I see, thanks!
___
*[geometry/optimization/hpolyhedron.cc, line 245 at r5](https://reviewable.io/reviews/alexandreamice/drake/12#-MteKsR28RSYsswZM-YE:-MtfEjMe3h5AwmhN7yqL:b-7d4s9l) ([raw file](https://github.com/alexandreamice/drake/blob/642b8a3807ce15f5d855f0cc090a95701b7697a2/geometry/optimization/hpolyhedron.cc#L245)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Done. 
</blockquote></details>

I probably didn't make myself clear. I mean when this program is infeasible, we don't know if this new constraint other.A().row(i)*x <= other.b().row(i) is redundant or not. If without this new constraint, the old program is already infeasible, then this new constraint is redundant. If the old program is feasible, and adding this new constraint makes it infeasible, then this new constraint is not redundant?
___
*[geometry/optimization/iris.h, line 174 at r4](https://reviewable.io/reviews/alexandreamice/drake/12#-MtWS2nr4_Mrm7q8r9A8:-MtfFWrs6R4k_jURuG4R:b-8qs58f) ([raw file](https://github.com/alexandreamice/drake/blob/cc05d7fc5fa287ec220571b72ebaadf10a58664f/geometry/optimization/iris.h#L174)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I am unsure whether we should enforce that the user must provide this option. In the rational forward kinematics code, you made the choice to force the user to specify q_star every time the function is called. My preference would be to force the user to declare the q_star on the construction of a RationalForwardKinematics object. 

In either case, given your code it would be consistent to demand that the user specify a q_star. However, I believe it is natural to assume the stereographic projection is taken at the 0 point unless there is a good reason for it not to be in which case defaulting to 0 would be the best option. What do you think?
</blockquote></details>

I think it is reasonable to use q_star as optional here, we just need to document what the default value means (that std::nullopt means using 0 as q_star).

BTW when I worked on rational_forward_kinematics, I was doing it for axis-aligned bounding box, then it is reasonable to change q_star to a non-zero value, and compute t = tan((q - q_star)/2) for the non-zero q_star. Since by changing q_star, what I get is just a box of t, which is still a box in the q-space.


<!-- Sent from Reviewable.io -->

2022-01-18 16:56 UTC, hongkai-dai reviewed
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/12)* status: 16 of 20 files reviewed, 3 unresolved discussions (waiting on @AlexandreAmice and @hongkai-dai)



<!-- Sent from Reviewable.io -->

2022-01-18 21:15 UTC, hongkai-dai requested changes
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/12)* status: 15 of 22 files reviewed, 4 unresolved discussions (waiting on @AlexandreAmice and @hongkai-dai)

___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1020 at r10](https://reviewable.io/reviews/alexandreamice/drake/12#-Mtj0im7An5wi_9SHbRN:-Mtj0im7An5wi_9SHbRO:b-da2c6e) ([raw file](https://github.com/alexandreamice/drake/blob/2cd7e18bd88748ead28468356718583215b3a939/multibody/rational_forward_kinematics/cspace_free_region.cc#L1020)):*
> ```cpp
>     const solvers::SolverOptions& solver_options,
>     Eigen::VectorXd* d_final) const {
>   // TODO (amice): This method tries to find the maximum expansion of the polytope. I tried to find the minimal tightening
> ```

I don't think this is a TODO. Our code already supports either to shrink the polytope if epsilon_max in BinarySearchOption is <= 0, or expand the polytope if epsilon_min in BinarySearchOption>= 0. 

So how about re-wording this documentation
```
This method supports both shrinking and expanding the polytope from C*t<=d_init. If search_option.epsilon_min>=0 then this method always expands the polytope C*t<=d_init + epsilon; if search_option.epsilon_max <= 0 then this method always shrink the polytope C*t<=d_init + epsilon.
```
___
*[sos_iris_certifier/iris_rational_cspace_test.ipynb, line 1 at r10](https://reviewable.io/reviews/alexandreamice/drake/12#-Mtj1_xh55hVRorW_yq3:-Mtj1_xh55hVRorW_yq4:b-9r35u9) ([raw file](https://github.com/alexandreamice/drake/blob/2cd7e18bd88748ead28468356718583215b3a939/sos_iris_certifier/iris_rational_cspace_test.ipynb#L1)):*
> ```
> {
> ```

BTW, Drake requires to clear all the notebook result before sending the PR.


<!-- Sent from Reviewable.io -->

2022-01-20 00:10 UTC, hongkai-dai requested changes
> Reviewed 3 of 5 files at r11.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/12)* status: 17 of 22 files reviewed, 4 unresolved discussions (waiting on @AlexandreAmice and @hongkai-dai)

___
*[geometry/optimization/hpolyhedron.cc, line 209 at r11](https://reviewable.io/reviews/alexandreamice/drake/12#-MtohdGb-lukklktCi0K:-MtohdGb-lukklktCi0L:b-yiysu0) ([raw file](https://github.com/alexandreamice/drake/blob/8a05573a20d64101d455a0d4d8338fb41bd6a5fd/geometry/optimization/hpolyhedron.cc#L209)):*
> ```cpp
>     result = solvers::Solve(prog);
> 
>     // constraints define an empty set or the current inequality of other is not redundant. Since we tested
> ```

Thanks for addressing the empty-set issue.

I think the dual approach might be easier than the currently implemented approach. Currently we need to solve two optimization programs to determine if the constraint is redundant. The dual approach only need to solve one program. Namely a constraint cᵀx≤ d is redundant given Ax≤ b, if and only if there exists dual variable λ, λ≥ 0, Aᵀλ=c, d −bᵀλ≥ 0. Could you add this as a TODO here and assign it to me? Thanks!
___
*[geometry/optimization/hpolyhedron.cc, line 273 at r11](https://reviewable.io/reviews/alexandreamice/drake/12#-Mtomre81aNOzlMw0ib5:-Mtomre81aNOzlMw0ib6:bg3bdrp) ([raw file](https://github.com/alexandreamice/drake/blob/8a05573a20d64101d455a0d4d8338fb41bd6a5fd/geometry/optimization/hpolyhedron.cc#L273)):*
> ```cpp
> 
>   int num_kept = num_inequalities;
>   std::unordered_set<int> kept_indices;
> ```

BTW, you don't have to use a separate variable `num_kept` here. Since you already have `kept_indices`, you can do `kept_indices.size()` in place of `num_kept`, and eliminates the risk of `num_kept` not synchronizing with `kept_indices`.
___
*[geometry/optimization/hpolyhedron.cc, line 299 at r11](https://reviewable.io/reviews/alexandreamice/drake/12#-MtonRBw9mm64AkXmFfF:-MtonRBx562JpANe3kfi:bsb97v1) ([raw file](https://github.com/alexandreamice/drake/blob/8a05573a20d64101d455a0d4d8338fb41bd6a5fd/geometry/optimization/hpolyhedron.cc#L299)):*
> ```cpp
>     prog.AddLinearCost(-A_.row(excluded_index), 0, x);
> 
>     auto result = solvers::Solve(prog);
> ```

You haven't checked if `result.is_sucess()`, what if this HPolyhedron is an empty set, then the next line `result.get_optimal_cost()` would return you a NAN.
___
*[geometry/optimization/test/hpolyhedron_test.cc, line 482 at r11](https://reviewable.io/reviews/alexandreamice/drake/12#-Mtont_3E77bGOFeC5sT:-Mtont_3E77bGOFeC5sU:biubfiw) ([raw file](https://github.com/alexandreamice/drake/blob/8a05573a20d64101d455a0d4d8338fb41bd6a5fd/geometry/optimization/test/hpolyhedron_test.cc#L482)):*
> ```cpp
>   Eigen::VectorXd b1(7);
>   //clang-format off
>   A0 <<    1.       ,  0.       ,   0.       ,
> ```

BTW, where do these numbers come from? It seems to me that you can probably create a simpler test example such that the two HPolyhedrons intersect (where the two HPolyhedron could even be 2D boxes), and the test would still pass. It is easier to maintain a test in the future if the test is simple.


<!-- Sent from Reviewable.io -->

2022-01-20 15:16 UTC, merged