C iris certify line for review
AlexandreAmice/drake pull request #55
Opened 2022-08-19 21:01 UTC by AlexandreAmice

2022-08-19 21:03 UTC, AlexandreAmice reviewed
+@hongkai-dai for review! You can ignore the python notebooks and we won't merge this. This can just give you an idea of the implementation

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/55#-:-N9ruTkzADU4kMy3e-oD:bv1ff66)* status: 0 of 23 files reviewed, all discussions resolved (waiting on @hongkai-dai)



<!-- Sent from Reviewable.io -->

2022-08-19 21:03 UTC, AlexandreAmice reviewed
+(do not merge) 

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/55#-:-N9rufUL8Ne0z-3PyusD:bnvsvbj)* status: 0 of 23 files reviewed, all discussions resolved (waiting on @hongkai-dai)



<!-- Sent from Reviewable.io -->

2022-08-21 02:28 UTC, hongkai-dai requested changes
Checkpoint

A high level idea (and maybe you have thought about this already):

I don't think we have to verify the straight line `mu * s0 + (1-mu) * s1`? As long as the path is parameterized as a univariate polynomial of `mu` then we can use the same condition that the univariate polynomial being sos. Namely we can write the path as `p(mu)` being a univariate polynomial of mu, with the constraint that `p(0) = s0` and `p(1) = s1`.  I think this is more general than the straight line in the stereographic projection `s` space? In may cases people won't plan their path as a straight line in the `s` space, but could be a straight line (or spline) in the original `q` space. This straight line in the original `q` space can be approximated by some polynomial in the `s` space.

When we start to use higher order polynomials to parameterize the path, then we don't have a straight line in the `s` space, hence we can't use separating hyperplane theorem on just the two boundary points `s0` and `s1`, but instead I think our separating hyperplane would also depend on `mu`, so previously our separating plane is
```
a(s) * s0 + b(s) >= 1
a(s) * s1 + b(s) >= 1
```
Now the condition becomes
```
a(μ) * p(μ) + b(μ) >=1 if 0 <= μ <= 1
```

> Reviewed 1 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/55#-:-N9wfJp85orGBGnJ-0QQ:bl0k5l8)* status: 1 of 23 files reviewed, 16 unresolved discussions (waiting on @AlexandreAmice and @hongkai-dai)

___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 32 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9wcijfE9Q5ephPeDjX:-N9wcijfE9Q5ephPeDjY:bw10o02) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L32)):*
> ```objc
>   }
> 
>   const symbolic::Polynomial get_p() const { return p_; }
> ```

return by a const reference to avoid the unnecessary copy
```cc
const symbolic::Polynomial& p() const { return p_; }
```
___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 36 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9wdJYW2Il1v9rUqwVK:-N9wdJYW2Il1v9rUqwVL:bl4om1g) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L36)):*
> ```objc
>  private:
>   //  a univariate polynomial q(μ) is nonnegative on [0, 1] if and
>   // only if q(μ) = λ(μ) + ν(μ)*μ*(1-μ) if deg(p) = 2d with deg(λ) ≤ 2d and
> ```

The symbol `p` doesn't appear before. Do you mean `deg(q)` here?
___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 37 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9wdtAVE-NqsC19wFwL:-N9wdtAVE-NqsC19wFwM:b2vlwpa) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L37)):*
> ```objc
>   //  a univariate polynomial q(μ) is nonnegative on [0, 1] if and
>   // only if q(μ) = λ(μ) + ν(μ)*μ*(1-μ) if deg(p) = 2d with deg(λ) ≤ 2d and
>   // deg(ν) ≤ 2d - 2 p(μ) = λ(μ)*μ + ν(μ)*(1-μ) if deg(p) = 2d + 1 with
> ```

Add a comma between 2d-2 and p(μ)?
___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 39 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9welVGBIRrMFzze3jm:-N9weBzc5OGYZ9jFoJEA:bhkqacm) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L39)):*
> ```objc
>   // deg(ν) ≤ 2d - 2 p(μ) = λ(μ)*μ + ν(μ)*(1-μ) if deg(p) = 2d + 1 with
>   // deg(λ) ≤ 2d and deg(ν) ≤ 2d and λ, ν are SOS. This polynomial is
>   // m_rational_numerator-q(μ)
> ```

`This polynomial` is ambiguous as there are many polynomials in this documentation, consider to be more explicit and document it as`p_ = m_rational_numerator - q(μ)`
___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 104 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9xQGWpAMlNBav-9g8j:-N9xQGWpAMlNBav-9g8k:b-x9bshm) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L104)):*
> ```objc
>           separating_plane_to_lorentz_cone_constraints) const;
> 
>   const symbolic::Variable get_mu() const { return mu_; }
> ```

Return const reference `const symbolic::Variable&`.
___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 105 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9xQON0AsWCTIonvyG6:-N9xQON0AsWCTIonvyG7:b-89a4l7) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L105)):*
> ```objc
> 
>   const symbolic::Variable get_mu() const { return mu_; }
>   const drake::VectorX<drake::symbolic::Variable> get_s0() const { return s0_; }
> ```

Ditto
___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 106 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9xQPqz0XMtFx8F-Osh:-N9xQPqz0XMtFx8F-Osi:b-89a4l7) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L106)):*
> ```objc
>   const symbolic::Variable get_mu() const { return mu_; }
>   const drake::VectorX<drake::symbolic::Variable> get_s0() const { return s0_; }
>   const drake::VectorX<drake::symbolic::Variable> get_s1() const { return s1_; }
> ```

Ditto
___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 108 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9xQS3WAs3w-XIevlnj:-N9xQS3WAs3w-XIevlnk:b-89a4l7) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L108)):*
> ```objc
>   const drake::VectorX<drake::symbolic::Variable> get_s1() const { return s1_; }
>   const std::list<CspaceLineTuple>* get_tuples() const { return &tuples_; }
>   const VectorX<symbolic::Variable> get_separating_plane_vars() const {
> ```

Ditto
___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 117 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9xQXJD5Lsz6e3vcwmx:-N9xQXJD5Lsz6e3vcwmy:b-eglhbp) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L117)):*
> ```objc
> 
>   /**
>    * Certifies whether the line μ*s₀ + (1−μ)*s₁. If the return is true, a formal
> ```

In complete sentence. Certifies whether the line ... is in the collision-free C-space
___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 130 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9xQknN3RYYHpTGrbtb:-N9xQknN3RYYHpTGrbtc:bnqmpbv) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L130)):*
> ```objc
>       const Eigen::Ref<const Eigen::VectorXd>& s1,
>       std::vector<SeparatingPlane<double>>* separating_planes_sol,
>       const solvers::SolverOptions& solver_options =
> ```

Google styleguide requires putting the mutable pointers after the immutable input. So I would suggest to remove the default value of `solver_options`, and change the API to
```cc
  std::vector<bool> CertifyTangentConfigurationSpaceLines(
      const Eigen::Ref<const Eigen::MatrixXd>& s0,
      const Eigen::Ref<const Eigen::MatrixXd>& s1,
      const solvers::SolverOptions& solver_options,
      std::vector<std::vector<SeparatingPlane<double>>>*
          separating_planes_sol_per_row) const;

```
___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 166 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9xwXzXEy1EMLlGkDXm:-N9xwXzXEy1EMLlGkDXn [...]

2022-08-22 19:15 UTC, AlexandreAmice reviewed
Yes I agree that in principle we can use this idea to certify any 1-d parametric polynomial path and the conditions would be very similar. My reasoning for only doing the straight line for now is two fold:
1.) It gives a very explicit toolbox for practioners to just say "grow an RRT/PRM in some abstract space and certify". The fact that it is in s vs q space I don't think will be as bothersome if we just wrap this up in this way.
2.) In the univariate case, I am hoping that we can say some slightly stronger statements than in more general cases. For example what degree do a(mu) and b(mu) such that infeasibility of the program proves there is some collision? Starting with straightlines will help restrict the problem enough that hopefully we can make stronger statements.

I am not sure I understand the point about "we can't use separating hyperplane theorem on just the two boundary points `s0` and `s1`". I am not just certifying the boundary points in this straight-line program either and even doing so would be insufficient for certifying the whole edge.

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/55#-:-NA5ppxD3wKFKWhtQbU-:b-11261n)* status: 1 of 23 files reviewed, 16 unresolved discussions (waiting on @hongkai-dai)

___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 32 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9wcijfE9Q5ephPeDjX:-NA5Zyux-yxDrJRtsx07:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L32)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

return by a const reference to avoid the unnecessary copy
```cc
const symbolic::Polynomial& p() const { return p_; }
```
</blockquote></details>

Done.
___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 36 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9wdJYW2Il1v9rUqwVK:-NA5_CyeDT3t4b-FvHa6:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L36)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

The symbol `p` doesn't appear before. Do you mean `deg(q)` here?
</blockquote></details>

Done.
___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 37 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9wdtAVE-NqsC19wFwL:-NA5_Gaq-TRKIaj8AJdm:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L37)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Add a comma between 2d-2 and p(μ)?
</blockquote></details>

Done.
___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 39 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9welVGBIRrMFzze3jm:-NA5_Q-L4H-UNU0hyduE:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L39)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`This polynomial` is ambiguous as there are many polynomials in this documentation, consider to be more explicit and document it as`p_ = m_rational_numerator - q(μ)`
</blockquote></details>

Done.
___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 104 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9xQGWpAMlNBav-9g8j:-NA5_nwMEXaicOPFIwa2:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L104)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Return const reference `const symbolic::Variable&`.
</blockquote></details>

Done.
___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 105 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9xQON0AsWCTIonvyG6:-NA5_oOYBnNVe8Un91Eg:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L105)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 106 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9xQPqz0XMtFx8F-Osh:-NA5_opiCiX8LPaWLtC-:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L106)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 108 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9xQS3WAs3w-XIevlnj:-NA5_pJiB9S8Pevj-to7:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L108)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 117 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9xQXJD5Lsz6e3vcwmx:-NA5_tP89VlozWvQkVrw:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L117)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

In complete sentence. Certifies whether the line ... is in the collision-free C-space
</blockquote></details>

Done.
___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 130 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9xQknN3RYYHpTGrbtb:-NA5bAgg4eDOtI_wZofX:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L130)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Google styleguide requires putting the mutable pointers after the immutable input. So I would suggest to remove the default value of `solver_options`, and change the API to
```cc
  std::vector<bool> CertifyTangentConfigurationSpaceLines(
      const Eigen::Ref<const Eigen::MatrixXd>& s0,
      const Eigen::Ref<const Eigen::MatrixXd>& s1,
      const solvers::SolverOptions& solver_options,
      std::vector<std::vector<SeparatingPlane<double>>>*
          separating_planes_sol_per_row) const;

```
</blockquote></details>

Done.
___
*[`multibody/rational_forward_kinematics/cspace_free_line.h` line 166 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9xwXzXEy1EMLlGkDXm:-NA5gKgo49vTnfscsh3H:b-nfagfa) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.h#L166)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry, what is `t` here?
</blockquote></details>

Moved this map into a method with documentation.
___
*[`multibody/rational_forward_kinematics/cspace_free_line.cc` line 70 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9xxkgv41hStpVdfZ2p:-NA5jd2h5ve4NGDRiGzW:b5eqpvp) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.cc#L70)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wr [...]

2022-08-24 04:00 UTC, hongkai-dai requested changes
Sorry I wasn't clear in my previous comment. I didn't mean to change the implementation in this PR. Just want to bring about the idea of certifying the higher order polynomial path as a food for thought. I think the math is pretty much the same as the straight line case, so it could be an easy extension.

Is there a proof on what degree of a(mu) and b(mu) should be for an if-and-only-if condition, that the infeasibility proves collision?

> I am not sure I understand the point about "we can't use separating hyperplane theorem on just the two boundary points s0 and s1". I am not just certifying the boundary points in this straight-line program either and even doing so would be insufficient for certifying the whole edge.

I had the wrong picture when I typed this, please ignore this comment.

> Reviewed 2 of 15 files at r3, 3 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/55#-:-NAAv9CG8dhbOD9QBKBl:b-zhz2bk)* status: 5 of 23 files reviewed, 7 unresolved discussions (waiting on @AlexandreAmice and @hongkai-dai)

___
*[`multibody/rational_forward_kinematics/cspace_free_line.cc` line 121 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9y3tCZ34aEmYJjJ9nI:-NAAy3XR-c0BfzPXQ58w:b-xwmc6q) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.cc#L121)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Since I am certifying a 1d polytope in mu then it is an axis aligned box in mu. Since we are subclassing from CspaceFreeRegion, I must specify a type or create a new enum value but since this is for all intents and purposes an `AxisAlignedBoundingBox` on the interval [0,1] I think this is fine.
</blockquote></details>

I see. Thanks for the explanation

I am rewriting our code from C_Iris branch into Drake master. While re-writing the code, I would like to make the following modifications
1. Remove the AxisAlignedBoundingBox. The axis-aligned bounding box simplifies the math a little bit, but makes the code more complicated, and I don't find it very useful.
2. Remove constant separating planes. So we only use linear function for separating planes for now, but could extend to higher degrees.  The constant separating plane would introduce lorentz cone constraints when we have non-polytopic collision geometries, while any non-constant separating plane would introduce matrix-sos constraint.
What do you think?
___
*[`multibody/rational_forward_kinematics/cspace_free_line.cc` line 321 at r4](https://reviewable.io/reviews/alexandreamice/drake/55#-NACDVyN-U83wSdO9qhs:-NACDVyN-U83wSdO9qht:b-uteps1) ([raw file](https://github.com/alexandreamice/drake/blob/14b6e825d0efd072c0a7f70b5d9fd7a2b6dc235b/multibody/rational_forward_kinematics/cspace_free_line.cc#L321)):*
> ```cpp
>   symbolic::Polynomial numerator_poly;
>   symbolic::Expression denominator_expr;
>   symbolic::Polynomial denominator_poly;
> ```

Curious why you need to convert the denominator to univariate polynomial also? I think we only need to verify the the numerator is non-negative when 0 <= mu <= 1? So I think we could use the original denominator (with `t` as indeterminates) without substituting with `mu`?
___
*[`multibody/rational_forward_kinematics/cspace_free_line.cc` line 472 at r4](https://reviewable.io/reviews/alexandreamice/drake/55#-NACxxxg869c9zOs3ag6:-NACxxxg869c9zOs3ag7:bamggjg) ([raw file](https://github.com/alexandreamice/drake/blob/14b6e825d0efd072c0a7f70b5d9fd7a2b6dc235b/multibody/rational_forward_kinematics/cspace_free_line.cc#L472)):*
> ```cpp
>     const Eigen::Ref<const Eigen::VectorXd>& s) const {
>   const Eigen::VectorXd s_min =
>       this->rational_forward_kinematics().plant().GetPositionLowerLimits();
> ```

I don't think this is the minimal or maximal of `s`? I thought s = tan((q-q*)/2), while here plant.GetPositionLowerLimits() and plant.GetPositionUpperLimits() return q_min and q_max.
___
*[`multibody/rational_forward_kinematics/cspace_free_region.h` line 696 at r4](https://reviewable.io/reviews/alexandreamice/drake/55#-NACzAeJ76ZRyw8CqT9r:-NACzAeKAu2n7ywhCV_n:b-257zyn) ([raw file](https://github.com/alexandreamice/drake/blob/14b6e825d0efd072c0a7f70b5d9fd7a2b6dc235b/multibody/rational_forward_kinematics/cspace_free_region.h#L696)):*
> ```objc
>    * t_upper - t.
>    */
>   static void ConstructTBoundsPolynomial(
> ```

I think it is better to add this as a free function instead of a static class method. When we have a parent class with a certain method, it means the derived class can also call this method. But I think in the derived class CspaceFreeLine, it doesn't have a notion of `t`, hence we should not call this method from the derived class, hence this function doesn't belong to CspaceFreeRegion.
___
*[`solvers/mathematical_program.cc` line 27 at r4](https://reviewable.io/reviews/alexandreamice/drake/55#-NAD-J1W9ioGubj_aIqd:-NAD-J1W9ioGubj_aIqe:b-51lyra) ([raw file](https://github.com/alexandreamice/drake/blob/14b6e825d0efd072c0a7f70b5d9fd7a2b6dc235b/solvers/mathematical_program.cc#L27)):*
> ```cpp
> #include "drake/solvers/decision_variable.h"
> #include "drake/solvers/sos_basis_generator.h"
> #include <iostream>
> ```

Revert this? We don't need iostream.
___
*[`solvers/mathematical_program.cc` line 255 at r4](https://reviewable.io/reviews/alexandreamice/drake/55#-NAD-LNhBXrFkFKbS3Vb:-NAD-LNhBXrFkFKbS3Vc:bcq0qtm) ([raw file](https://github.com/alexandreamice/drake/blob/14b6e825d0efd072c0a7f70b5d9fd7a2b6dc235b/solvers/mathematical_program.cc#L255)):*
> ```cpp
>   const symbolic::Polynomial p =
>       ComputePolynomialFromMonomialBasisAndGramMatrix(monomial_basis, gramian);
> ```

Revert this?
___
*[`solvers/mathematical_program.cc` line 268 at r4](https://reviewable.io/reviews/alexandreamice/drake/55#-NAD-8ni8NaYQ5EJ6U8f:-NAD-8nj4Gss_pYd4n2y:b23votb) ([raw file](https://github.com/alexandreamice/drake/blob/14b6e825d0efd072c0a7f70b5d9fd7a2b6dc235b/solvers/mathematical_program.cc#L268)):*
> ```cpp
>       AddPositiveDiagonallyDominantMatrixConstraint(
>           gramian.cast<symbolic::Expression>());
>       break;
> ```

Could you revert this change? I think it would conflict with the master once https://reviewable.io/reviews/RobotLocomotion/drake/17754#- is merged.


<!-- Sent from Reviewable.io -->

2022-08-24 14:20 UTC, AlexandreAmice reviewed
Gotcha. The scalability of higher degree polynomial splines may be challenging. The degree of the univariate polynomial will be `deg(path) * deg(plant)` and is so barring a more specialized solver (maybe a Burrer-Monteiro based one?) it might be difficult to get reasonable run times.

I am working on the proof of the if-and-only-if condition with Pablo. It seems somewhat tricky but could be a very nice result if we can prove something.

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/55#-:-NAF3GRfBZTVzSQdPS7h:b-g976l4)* status: 5 of 23 files reviewed, 7 unresolved discussions (waiting on @hongkai-dai)

___
*[`multibody/rational_forward_kinematics/cspace_free_line.cc` line 121 at r3](https://reviewable.io/reviews/alexandreamice/drake/55#-N9y3tCZ34aEmYJjJ9nI:-NAF3zBH3AMd8dEIDR9M:bngv5zu) ([raw file](https://github.com/alexandreamice/drake/blob/a9567a18761f0ef73616a3f90755136976c42f21/multibody/rational_forward_kinematics/cspace_free_line.cc#L121)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see. Thanks for the explanation

I am rewriting our code from C_Iris branch into Drake master. While re-writing the code, I would like to make the following modifications
1. Remove the AxisAlignedBoundingBox. The axis-aligned bounding box simplifies the math a little bit, but makes the code more complicated, and I don't find it very useful.
2. Remove constant separating planes. So we only use linear function for separating planes for now, but could extend to higher degrees.  The constant separating plane would introduce lorentz cone constraints when we have non-polytopic collision geometries, while any non-constant separating plane would introduce matrix-sos constraint.
What do you think?
</blockquote></details>

1.) Perhaps an alternative would be to remove the enumerated type completely and make the `AxisAlignedBoundingBox` a subclass of `CspaceFreeRegion` in the same way I intend to make `CspaceFreeLine` a subclass

2.) I think this decision is purely a matter of whether leaving the constant planes saves much, if any computation. When certifying line segments, I could imagine that the constant hyperplanes are more likely to actually succeed in certifying regions than would be the case in more general regions, but this may not be practical from a code perspective especially if it save no time.
___
*[`multibody/rational_forward_kinematics/cspace_free_line.cc` line 321 at r4](https://reviewable.io/reviews/alexandreamice/drake/55#-NACDVyN-U83wSdO9qhs:-NAF8rd--mWrkLfMvfxt:b-e85138) ([raw file](https://github.com/alexandreamice/drake/blob/14b6e825d0efd072c0a7f70b5d9fd7a2b6dc235b/multibody/rational_forward_kinematics/cspace_free_line.cc#L321)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Curious why you need to convert the denominator to univariate polynomial also? I think we only need to verify the the numerator is non-negative when 0 <= mu <= 1? So I think we could use the original denominator (with `t` as indeterminates) without substituting with `mu`?
</blockquote></details>

good point.
___
*[`multibody/rational_forward_kinematics/cspace_free_line.cc` line 472 at r4](https://reviewable.io/reviews/alexandreamice/drake/55#-NACxxxg869c9zOs3ag6:-NAF8vHG9cyHv7IPqSy2:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/14b6e825d0efd072c0a7f70b5d9fd7a2b6dc235b/multibody/rational_forward_kinematics/cspace_free_line.cc#L472)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I don't think this is the minimal or maximal of `s`? I thought s = tan((q-q*)/2), while here plant.GetPositionLowerLimits() and plant.GetPositionUpperLimits() return q_min and q_max.
</blockquote></details>

Done.
___
*[`multibody/rational_forward_kinematics/cspace_free_region.h` line 696 at r4](https://reviewable.io/reviews/alexandreamice/drake/55#-NACzAeJ76ZRyw8CqT9r:-NAFBVmL17Dw2ywjG6ww:b1b3b4h) ([raw file](https://github.com/alexandreamice/drake/blob/14b6e825d0efd072c0a7f70b5d9fd7a2b6dc235b/multibody/rational_forward_kinematics/cspace_free_region.h#L696)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think it is better to add this as a free function instead of a static class method. When we have a parent class with a certain method, it means the derived class can also call this method. But I think in the derived class CspaceFreeLine, it doesn't have a notion of `t`, hence we should not call this method from the derived class, hence this function doesn't belong to CspaceFreeRegion.
</blockquote></details>

Done. Left over from a prototype version of the code. Thanks for catching this
___
*[`solvers/mathematical_program.cc` line 27 at r4](https://reviewable.io/reviews/alexandreamice/drake/55#-NAD-J1W9ioGubj_aIqd:-NAFBVPw17wZqOkrwHAU:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/14b6e825d0efd072c0a7f70b5d9fd7a2b6dc235b/solvers/mathematical_program.cc#L27)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Revert this? We don't need iostream.
</blockquote></details>

Done.
___
*[`solvers/mathematical_program.cc` line 255 at r4](https://reviewable.io/reviews/alexandreamice/drake/55#-NAD-LNhBXrFkFKbS3Vb:-NAFBvxr6RfRhfFj0HmQ:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/14b6e825d0efd072c0a7f70b5d9fd7a2b6dc235b/solvers/mathematical_program.cc#L255)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Revert this?
</blockquote></details>

Done.
___
*[`solvers/mathematical_program.cc` line 268 at r4](https://reviewable.io/reviews/alexandreamice/drake/55#-NAD-8ni8NaYQ5EJ6U8f:-NAFBwOs82uhz7VnsJGP:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/14b6e825d0efd072c0a7f70b5d9fd7a2b6dc235b/solvers/mathematical_program.cc#L268)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you revert this change? I think it would conflict with the master once https://reviewable.io/reviews/RobotLocomotion/drake/17754#- is merged.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-24 16:56 UTC, hongkai-dai requested changes
Interesting. I thought that since now the polynomial is uni-variate, we can afford higher degrees compared to multivariate case, as the size of the PSD is nchoosek(n+d, d). I definitely agree trying a more specialized solver would be great, for example the Burrer-Monteiro based solver, even for the simple straight line case.

I think you replied the comments, but I haven't seen the new commits yet? The newest commit was still on Aug 22.

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/55#-:-NAFlQfb2bXTJut-3UyR:b-wo4sg7)* status: 5 of 23 files reviewed, 7 unresolved discussions (waiting on @AlexandreAmice and @hongkai-dai)

___
*[`multibody/rational_forward_kinematics/cspace_free_line.cc` line 321 at r4](https://reviewable.io/reviews/alexandreamice/drake/55#-NACDVyN-U83wSdO9qhs:-NAFl5yg77P6RItqzpnp:b-lhtroz) ([raw file](https://github.com/alexandreamice/drake/blob/14b6e825d0efd072c0a7f70b5d9fd7a2b6dc235b/multibody/rational_forward_kinematics/cspace_free_line.cc#L321)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

good point.
</blockquote></details>

It is still doing substitution on the denominator?


<!-- Sent from Reviewable.io -->

2022-08-24 17:39 UTC, AlexandreAmice reviewed
We can certainly afford much higher degrees. Once I can fix the long substitution times on some of the higher degree plants it will be interesting to see just how high a degree is reasonable.

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/55#-:-NAFvt33Anu7zjIw-vBG:brh8dub)* status: 1 of 23 files reviewed, 7 unresolved discussions (waiting on @hongkai-dai)

___
*[`multibody/rational_forward_kinematics/cspace_free_line.cc` line 321 at r4](https://reviewable.io/reviews/alexandreamice/drake/55#-NACDVyN-U83wSdO9qhs:-NAFw1zW0cmsbyP0lqEt:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/14b6e825d0efd072c0a7f70b5d9fd7a2b6dc235b/multibody/rational_forward_kinematics/cspace_free_line.cc#L321)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It is still doing substitution on the denominator?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-25 17:24 UTC, hongkai-dai reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 6 files at r4, 4 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/55#-:-NAL1ErQ3CpI4S5_YdL7:bg7igkv)* status: 6 of 23 files reviewed, all discussions resolved (waiting on @hongkai-dai)



<!-- Sent from Reviewable.io -->

2022-08-26 18:12 UTC, merged